#!/usr/bin/env python3
# filename: videoui_server.py
# description: Sprint15 customer download UI — stdlib HTTP gallery (D-S15-9).
"""
Sprint15 video gallery/download server. stdlib http.server ONLY — no
framework, no pip installs, no database: manifest.json IS the state,
regenerated by video_manifest at every clip boundary.

Routes:
  /                  the gallery page (single static HTML, inline JS)
  /manifest.json     the clip list (newest first)
  /videos/<name>     clip MP4s and poster JPEGs, with single-range HTTP
                     Range support (iPhone Safari scrubbing needs 206s)

Serving rules (defensive, the unit may sit on an open AP later):
  - only basenames, only .mp4/.jpg, only inside the video directory
  - no directory listings, no dotfiles, GET/HEAD only

Runs as a daemon thread of the video runtime when video.ui.enabled
(default port 8080); binds 0.0.0.0 so it serves the LAN today and the
`wap` AP later without change.
"""

import html
import json
import os
import posixpath
import subprocess
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, unquote, urlparse

import video_settings

ALLOWED_SUFFIXES = (".mp4", ".jpg")

GALLERY_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>bmcam video</title>
<style>
 body{margin:0;font-family:-apple-system,system-ui,sans-serif;
      background:#10151c;color:#e8edf2}
 header{padding:14px 18px;background:#1a2230;position:sticky;top:0}
 h1{margin:0;font-size:18px} #meta{color:#8fa1b3;font-size:13px}
 #grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));
       gap:12px;padding:14px}
 .card{background:#1a2230;border-radius:10px;overflow:hidden}
 .card img{width:100%;aspect-ratio:16/9;object-fit:cover;display:block;
           background:#2a3444;cursor:pointer}
 .noThumb{width:100%;aspect-ratio:16/9;display:flex;align-items:center;
          justify-content:center;background:#2a3444;color:#8fa1b3;
          font-size:12px;cursor:pointer}
 .card .info{padding:8px 10px;font-size:12px;line-height:1.5}
 .name{word-break:break-all;color:#cfe0f0}
 .sub{color:#8fa1b3}
 a.dl{display:inline-block;margin-top:6px;padding:4px 10px;background:#2d6cdf;
      color:#fff;border-radius:6px;text-decoration:none;font-size:12px}
 #player{position:fixed;inset:0;background:rgba(0,0,0,.92);display:none;
         align-items:center;justify-content:center;flex-direction:column}
 #player video{max-width:96vw;max-height:80vh;background:#000}
 #player .bar{color:#cfe0f0;font-size:13px;padding:10px;word-break:break-all}
 #player button{margin-left:12px;padding:4px 12px}
</style>
</head>
<body>
<header><h1>bmcam video
  <a href="/settings" style="float:right;font-size:13px;color:#7fb0e8">
    ⚙ Settings</a></h1>
  <div id="meta">loading manifest…</div></header>
<div id="grid"></div>
<div id="player">
  <div class="bar"><span id="pname"></span>
    <button onclick="closePlayer()">close</button></div>
  <video id="pvideo" controls playsinline></video>
</div>
<script>
function fmtMB(b){return (b/1048576).toFixed(1)+" MB"}
function fmtDur(s){if(s==null)return "";const m=Math.floor(s/60);
  return m+":"+String(s%60).padStart(2,"0")}
function openPlayer(name){
  document.getElementById("pname").textContent=name;
  const v=document.getElementById("pvideo");
  v.src="/videos/"+encodeURIComponent(name);
  document.getElementById("player").style.display="flex"; v.play();}
function closePlayer(){const v=document.getElementById("pvideo");
  v.pause(); v.removeAttribute("src"); v.load();
  document.getElementById("player").style.display="none";}
fetch("/manifest.json").then(r=>r.json()).then(m=>{
  document.getElementById("meta").textContent=
    m.count+" clips (newest first)";
  const g=document.getElementById("grid");
  for(const c of m.clips){
    const card=document.createElement("div"); card.className="card";
    const thumb=c.thumb
      ?`<img loading="lazy" src="/videos/${encodeURIComponent(c.thumb)}"
           onclick="openPlayer('${c.name}')">`
      :`<div class="noThumb" onclick="openPlayer('${c.name}')">no preview</div>`;
    card.innerHTML=thumb+
      `<div class="info"><div class="name">${c.name}</div>`+
      `<div class="sub">${fmtMB(c.bytes)} · ${fmtDur(c.dur)}`+
      `${c.res?" · "+c.res:""}</div>`+
      `<a class="dl" href="/videos/${encodeURIComponent(c.name)}" `+
      `download>Download</a></div>`;
    g.appendChild(card);}
}).catch(e=>{document.getElementById("meta").textContent=
  "manifest error: "+e});
</script>
</body>
</html>
"""


SETTINGS_CSS = """
 body{margin:0;font-family:-apple-system,system-ui,sans-serif;
      background:#10151c;color:#e8edf2}
 header{padding:14px 18px;background:#1a2230}
 h1{margin:0;font-size:18px}
 main{max-width:560px;margin:0 auto;padding:14px}
 .field{background:#1a2230;border-radius:10px;padding:12px 14px;
        margin-bottom:10px}
 label{display:block;font-size:14px;color:#cfe0f0;margin-bottom:6px;
       font-weight:600}
 select{width:100%;padding:8px;font-size:15px;border-radius:6px;
        background:#243044;color:#e8edf2;border:1px solid #38465c}
 .help{font-size:12px;color:#8fa1b3;margin-top:6px;line-height:1.4}
 button,a.btn{display:inline-block;padding:10px 18px;margin:8px 8px 0 0;
        font-size:15px;border-radius:8px;border:none;cursor:pointer;
        text-decoration:none}
 .save{background:#2d6cdf;color:#fff}
 .restart{background:#b3552d;color:#fff}
 .back{background:#243044;color:#cfe0f0}
 .notice{background:#233c26;border-radius:10px;padding:12px 14px;
         margin-bottom:10px;font-size:14px}
 .error{background:#4a2323}
"""


def render_settings_page(current, message=None, error=False):
    """The /settings form, values pre-selected from the live YAML."""
    rows = []
    if message:
        rows.append(f'<div class="notice{" error" if error else ""}">'
                    f'{html.escape(message)}</div>')
    rows.append('<form method="POST" action="/settings">')
    for field in video_settings.FIELDS:
        key = field["key"]
        cur = current.get(key)
        # Match the current value to its canonical choice NUMERICALLY
        # (YAML 2.0 == dropdown "2") so the form never submits a
        # non-canonical echo — the bmcam000 2026-08-18 save-poison bug.
        selected = (video_settings.normalize_choice(key, cur)
                    if cur is not None else None)
        options = list(field["choices"])
        if cur is not None and selected is None:
            # Genuinely off-menu value: show it honestly.
            selected = str(cur)
            options.insert(0, (str(cur), f"current: {cur}"))
        opts = "".join(
            f'<option value="{html.escape(v)}"'
            f'{" selected" if v == selected else ""}>'
            f'{html.escape(label)}</option>'
            for v, label in options)
        missing = "" if cur is not None else (
            '<div class="help">! not present in this config file '
            '(shown for reference, not editable)</div>')
        disabled = "" if cur is not None else " disabled"
        rows.append(
            f'<div class="field"><label>{html.escape(field["label"])}'
            f'</label><select name="{html.escape(key)}"{disabled}>{opts}'
            f'</select><div class="help">{html.escape(field["help"])}'
            f'</div>{missing}</div>')
    rows.append('<button class="save" type="submit">Save settings</button>'
                '<a class="btn back" href="/">Back to videos</a></form>')
    rows.append(
        '<form method="POST" action="/restart" '
        'onsubmit="return confirm(\'Restart the camera now? Recording '
        'resumes automatically about a minute later.\')">'
        '<button class="restart" type="submit">Restart camera '
        '(apply saved settings)</button></form>')
    body = "\n".join(rows)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>bmcam settings</title><style>{SETTINGS_CSS}</style></head>
<body><header><h1>bmcam settings</h1></header><main>
<div class="help" style="margin-bottom:10px">Saved changes take effect
when the camera restarts. A timestamped backup of the config is kept on
the camera before every save.</div>
{body}</main></body></html>"""


def _default_restart():
    """Reboot the camera (cron @reboot restarts recording — the pipeline
    is crash-safe, so this is always a clean apply path)."""
    subprocess.Popen(["sudo", "-n", "/sbin/reboot"])


class VideoUIHandler(BaseHTTPRequestHandler):
    # Set by the server factory.
    video_dir = None
    config_path = None            # None = settings page disabled (404)
    restart_fn = staticmethod(_default_restart)
    protocol_version = "HTTP/1.1"

    # ------------------------------------------------------------------
    def log_message(self, fmt, *args):  # quiet: cron log is for clips
        pass

    def _send_bytes(self, code, body, content_type, extra=None):
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _resolve(self, name):
        """Basename-only, allowed suffixes, inside video_dir — or None."""
        name = os.path.basename(unquote(name))
        if not name or name.startswith("."):
            return None
        if not name.lower().endswith(ALLOWED_SUFFIXES):
            return None
        if name.endswith(".part") or name.endswith(".tmp"):
            return None
        path = os.path.realpath(os.path.join(self.video_dir, name))
        if os.path.dirname(path) != os.path.realpath(self.video_dir):
            return None
        return path if os.path.isfile(path) else None

    def _parse_range(self, size):
        """Single-range 'bytes=a-b' -> (start, end) inclusive, or None."""
        header = self.headers.get("Range")
        if not header or not header.startswith("bytes="):
            return None
        spec = header[len("bytes="):].split(",")[0].strip()
        try:
            start_s, _, end_s = spec.partition("-")
            if start_s == "" and end_s:            # suffix: last N bytes
                n = min(int(end_s), size)
                return (size - n, size - 1) if n > 0 else None
            start = int(start_s)
            end = int(end_s) if end_s else size - 1
            if start >= size or start < 0 or end < start:
                return "invalid"
            return (start, min(end, size - 1))
        except ValueError:
            return "invalid"

    def _serve_file(self, path):
        size = os.path.getsize(path)
        ctype = "video/mp4" if path.endswith(".mp4") else "image/jpeg"
        rng = self._parse_range(size)
        if rng == "invalid":
            self._send_bytes(
                416, b"", ctype, {"Content-Range": f"bytes */{size}"})
            return
        with open(path, "rb") as f:
            if rng is None:
                self.send_response(200)
                self.send_header("Content-Type", ctype)
                self.send_header("Content-Length", str(size))
                self.send_header("Accept-Ranges", "bytes")
                self.end_headers()
                if self.command != "HEAD":
                    self._copy(f, size)
                return
            start, end = rng
            length = end - start + 1
            f.seek(start)
            self.send_response(206)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(length))
            self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
            self.send_header("Accept-Ranges", "bytes")
            self.end_headers()
            if self.command != "HEAD":
                self._copy(f, length)

    def _copy(self, f, length, block=1 << 16):
        remaining = length
        while remaining > 0:
            chunk = f.read(min(block, remaining))
            if not chunk:
                break
            try:
                self.wfile.write(chunk)
            except (BrokenPipeError, ConnectionResetError):
                return  # Safari aborts Range reads constantly; not an error
            remaining -= len(chunk)

    # ------------------------------------------------------------------
    def _send_settings(self, message=None, error=False):
        current = video_settings.read_current(self.config_path)
        page = render_settings_page(current, message=message, error=error)
        self._send_bytes(200, page.encode("utf-8"),
                         "text/html; charset=utf-8")

    def do_POST(self):
        try:
            path = posixpath.normpath(urlparse(self.path).path)
            if self.config_path is None:
                self._send_bytes(404, b"not found", "text/plain")
                return
            if path == "/restart":
                print("[UI] restart requested from the settings page")
                try:
                    type(self).restart_fn()
                except Exception as exc:
                    self._send_settings(f"Restart failed: {exc}", error=True)
                    return
                self._send_bytes(
                    200,
                    b"<meta charset='utf-8'>Restarting &mdash; the camera "
                    b"and this page come back in about a minute. "
                    b"<a href='/'>Reload</a>",
                    "text/html; charset=utf-8")
                return
            if path == "/settings":
                length = int(self.headers.get("Content-Length", 0) or 0)
                form = parse_qs(
                    self.rfile.read(length).decode("utf-8", errors="replace"))
                changes = {k: v[0] for k, v in form.items() if v}
                try:
                    result = video_settings.patch_yaml(
                        self.config_path, changes)
                except Exception as exc:
                    print(f"[UI][WARN] settings save rejected: {exc}")
                    self._send_settings(f"NOT saved: {exc}", error=True)
                    return
                if result["changed"]:
                    changed = ", ".join(result["changed"])
                    print(f"[UI] settings saved: {changed} "
                          f"(backup {result['backup']})")
                    self._send_settings(
                        f"Saved: {changed}. Takes effect at the next "
                        "camera restart.")
                else:
                    self._send_settings("No changes.")
                return
            self._send_bytes(404, b"not found", "text/plain")
        except (BrokenPipeError, ConnectionResetError):
            pass

    def do_GET(self):
        try:
            path = urlparse(self.path).path
            path = posixpath.normpath(path)
            if path in ("/", "/index.html"):
                self._send_bytes(200, GALLERY_HTML.encode("utf-8"),
                                 "text/html; charset=utf-8")
                return
            if path == "/settings":
                if self.config_path is None:
                    self._send_bytes(404, b"not found", "text/plain")
                    return
                self._send_settings()
                return
            if path == "/manifest.json":
                mpath = os.path.join(self.video_dir, "manifest.json")
                if os.path.isfile(mpath):
                    with open(mpath, "rb") as f:
                        body = f.read()
                else:
                    body = json.dumps(
                        {"schema": "bmcam_video_manifest_v1",
                         "count": 0, "clips": []}).encode("utf-8")
                self._send_bytes(200, body, "application/json",
                                 {"Cache-Control": "no-store"})
                return
            if path.startswith("/videos/"):
                resolved = self._resolve(path[len("/videos/"):])
                if resolved is None:
                    self._send_bytes(404, b"not found", "text/plain")
                    return
                self._serve_file(resolved)
                return
            self._send_bytes(404, b"not found", "text/plain")
        except (BrokenPipeError, ConnectionResetError):
            pass

    do_HEAD = do_GET


def start_ui_server(video_dir, port, host="0.0.0.0", config_path=None,
                    restart_fn=None):
    """Start the gallery server on a daemon thread; returns the server
    (call .shutdown() to stop). Raises on bind failure — the CALLER
    decides that a dead UI must not kill recording. config_path enables
    the /settings editor page (None = gallery only)."""
    attrs = {"video_dir": os.path.realpath(video_dir),
             "config_path": config_path}
    if restart_fn is not None:
        attrs["restart_fn"] = staticmethod(restart_fn)
    handler = type("BoundVideoUIHandler", (VideoUIHandler,), attrs)
    server = ThreadingHTTPServer((host, int(port)), handler)
    server.daemon_threads = True
    thread = threading.Thread(
        target=server.serve_forever, name="videoui", daemon=True)
    thread.start()
    print(f"[UI] gallery serving on {host}:{server.server_address[1]} "
          f"(dir={video_dir})")
    return server
