#!/usr/bin/env python3
# filename: gen_command_reference.py
# description: Sprint26 S4 c.4 — generate docs/bmcam_command_reference.md (commands v9) from the registry and the wire module.
"""
Generate the bmcam command reference (commands v9) from the SAME data the unit
uses: config_registry (every setting, type, default, range, apply timing, guard
class, short name, presets, one-shot keys) and command_wire (id ranges, size
limits, error codes). A hand edit would drift; tests/test_s4_command_reference.py
fails when the committed doc differs from this output.

Inputs:  none (reads BM_Devel_Pi modules).
Outputs: docs/bmcam_command_reference.md (--write), or the text on stdout.
Example:
  .venv-dev/bin/python tools/gen_command_reference.py --write
Known limitations: the v8 verbs (legacy runtime only, until S5) are listed as
a retired mapping, not documented in full.
"""

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "BM_Devel_Pi"))

import command_guards as G  # noqa: E402
import command_wire as W  # noqa: E402
import config_registry as R  # noqa: E402

OUT = os.path.join(REPO, "docs", "bmcam_command_reference.md")

RETIRED = [("roi", "still.crop (r)"), ("foc", "camera.focus.* (f = mode)"),
           ("awb", "camera.white_balance.mode (b)"), ("exp", "camera.exposure.ev (e)"),
           ("win", "still.budget_min / video.send.budget_min"),
           ("txd", "uplink.msg_interval_s"), ("cap", "still.message_cap (m)"),
           ("src", "trg v 3/4 (one-shot only)"), ("hlt", "power.halt.*"),
           ("twn", "schedule.window.*"), ("tmz", "schedule.timezone"), ("cfg", "get")]

GUARD_TEXT = {
    R.GUARDED_REVERT: "applies at once; reverts unless `cfm`",
    R.GUARDED_STAGE: "staged until `cfm` (ack `s:1`)",
    R.LOCKED: "not settable by command (deploy only)",
    R.SERVICE: "signed service command only (then reverts unless `cfm`)",
}


def _cell(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return "[" + ", ".join(_cell(v) for v in value) + "]"
    text = str(value)
    return text.replace("|", "\\|") if text else '""'


def _domain(key):
    if key.enum:
        return " / ".join(_cell(e) for e in key.enum)
    if key.range:
        return f"{key.range[0]} – {key.range[1]}"
    return key.type


def _guard(key):
    if key.guard == R.NONE:
        return ""
    when = "" if key.guard_when is None else " when " + " / ".join(_cell(v) for v in key.guard_when)
    return f"{key.guard}{when}"


def render():
    L = ["# bmcam command reference (commands v9)", "",
         "GENERATED by `tools/gen_command_reference.py` from `BM_Devel_Pi/config_registry.py` "
         f"(registry v{R.REGISTRY_VERSION}) and `BM_Devel_Pi/command_wire.py`. Do not edit by "
         "hand: change the code and regenerate (`--write`); a test fails when this file is stale.",
         "",
         "v9 runs on the **supervisor runtime of a migrated (config v2) unit**. The legacy runtime "
         "(and the video_logger recorder) still speak the v8 preset verbs until the legacy runtime "
         "is deleted after S5 (PLAN_S4.md G1).", "",
         "## How to send", "",
         "At the Spotter console (or through the Sofar command API as the same line):", "",
         "```text", 'bm pub bmcam/cmd {"id":1000001,"c":"get","k":["mode"]} 1 1', "```", "",
         f"- The JSON is at most **{W.MAX_JSON_BYTES} bytes** including `sig`; the whole console "
         f"line at most **{W.MAX_CONSOLE_LINE_BYTES} bytes** (the Sofar limit).",
         "- Strict JSON: ASCII only, finite numbers (no NaN), no duplicate keys, `true`/`false` "
         "are not numbers, strings `[A-Za-z0-9_:./+-]{1,48}`, lists of 1–4 numbers or names, "
         "objects only at the top and as `kv`.",
         "- Every answer is printed on the Spotter console for a person; a cellular ack goes only "
         "for the remote and service id ranges.", "",
         "## Command ids (who sends what)", "",
         "| range | sender | cellular answer | high-water |", "|---|---|---|---|"]
    who = {"console": "console by hand, dev_mode.sh", "heal": "backend heals (rsd)",
           "remote": "dashboard, bench GUI, sofar_send_command",
           "service": "signed service commands (bm_service_sign.py)",
           "conductor": "bench conductor"}
    for name, lo, hi, hw, cell in W.RANGES:
        L.append(f"| {lo:,} – {hi:,} | {who[name]} | {'yes' if cell else 'no (console)'} | "
                 f"{'yes' if hw else 'no'} |")
    L += ["", "A re-sent id returns its ORIGINAL answer with `\"d\":1` (256 kept). In a high-water "
          "range an older id is refused `e:\"old\"`. A service-range id always needs a valid "
          "`sig`.", "",
          "## Verbs", "",
          "| verb | example | effect |", "|---|---|---|",
          '| `ping` | `{"id":N,"c":"ping"}` | liveness |',
          '| `help` | `{"id":N,"c":"help"}` | this summary on the console |',
          '| `get` | `{"id":N,"c":"get","k":["mode","r"]}` | values + source (console; `<CF>` '
          'for a cellular id, at most 3 parts); `"k":["journal"]` = the last 5 changes; '
          '`"to":"con"` = console only |',
          '| `set` | `{"id":N,"c":"set","kv":{"m":150,"camera.exposure.ev":-1.0}}` | '
          'all-or-none, the whole resulting config validated; `"b":"<hash8>"` = compare-and-set |',
          '| `reset` | `{"id":N,"c":"reset","k":["m"]}` / `{"all":1}` | back to the YAML value '
          '(a key, short name or group) |',
          '| `cfm` | `{"id":N,"c":"cfm","ref":<set id>}` | confirms a guarded `set` |',
          '| `trg` | `{"id":N,"c":"trg","v":2,"kv":{"d":8}}` | one action now: 0 cancel, 1 '
          'capture + save, 2 capture + output per mode, 3 stored reef reference, 4 stored '
          'reference card; `kv` = one-shot keys for that action only (never saved) |',
          '| `hld` | `{"id":N,"c":"hld","v":30}` | stay awake v min (0 releases); the ack\'s `v` '
          'is the minutes granted; never saved |',
          '| `rsd` | from the backend heal-commands endpoint | re-send chunks (heals) |',
          '| `wap` | `{"id":N,"c":"wap","v":1}` | 0 boot default, 1 open hotspot 60 min, 2 HQ WiFi '
          '60 min |', "",
          "Keep-alive: every command received keeps a per_boot unit up `commands.keepalive_s` "
          "after it (at most `commands.keepalive_max_s`), within the bus-power budget unless "
          "`power.bus_always_on`.", "",
          "## Answers", "",
          "- Ack: `{\"id\":N,\"ok\":1,\"h\":\"<hash8>\"}`; plus `e`/`k` on a rejection, `s:1` "
          "staged, `d:1` duplicate, `v` granted hold minutes. `h` = the config fingerprint "
          "after the command.",
          "- `<CF v=1 h=<hash8> [n=i/N] key=value[@source] ...>`: `get` answers, the keys a set "
          "changed, `reverted=` / `err=` reports. Source `@c<id>` = set by that command, `@v8` = "
          "folded from the v8 state, `@d` = registry default, none = the YAML.",
          "- `<WS ... cfg=<hash8> up=<s> ...>` and START `cfg=` carry the hash; a triggered START "
          "also `tg=<id>` and the resolved `r=`/`m=`/`d=`.", "",
          "| e | meaning |", "|---|---|"]
    L += [f"| `{code}` | {text} |" for code, text in W.ERROR_CODES.items()]
    L += ["", "## Guarded keys", "",
          f"- `guarded_revert`: reverts after {G.ACTIONS_LIMIT} transmitting actions or "
          f"{G.BOOTS_LIMIT} boots without `cfm`, and after "
          f"{int(G.SAVE_LOCAL_UPTIME_S // 3600)} h of uptime in any case (`mode.output` save_local: "
          f"{G.BOOTS_LIMIT} boots or {int(G.SAVE_LOCAL_UPTIME_S // 3600)} h). The revert is "
          "reported as `<CF reverted=<key>>`.",
          "- `guarded_stage`: stored, not applied, until `cfm`.",
          "- `locked`: deploy only. `service`: a signed service-range command "
          "(`tools/bm_service_sign.py`), then as guarded_revert.", "",
          "| key | class | effect |", "|---|---|---|"]
    for key in R.KEYS:
        if key.guard != R.NONE:
            L.append(f"| `{key.path}` | {_guard(key)} | {GUARD_TEXT[key.guard]} |")
    L += ["", "## Short names", "", "| short | key |", "|---|---|"]
    for short, path in sorted(R.SHORT_NAMES.items()):
        L.append(f"| `{short}` | `{path}` |")
    L += ["| `m` | message cap of the media in play: " + ", ".join(
        f"`{p}` ({m})" for m, p in R.MEDIA_SHORT["m"].items()) + " |", "",
        "## One-shot keys (`trg kv`)", "",
        "Only these may be overridden for one action (never saved; re-checked at action time): "
        + ", ".join(f"`{p}`" for p in R.ONE_SHOT) + ". `med` = the other media for one action.", ""]
    L += ["## Settings", "",
          "`apply`: next_action = the next capture/decision point; next_boot = the next boot "
          "(stay_on restarts itself for it).", ""]
    for group in R.groups():
        L += [f"### {group}", "", "| key | type | default | allowed | apply | guard | "
              "meaning | presets |", "|---|---|---|---|---|---|---|---|"]
        for key in R.KEYS:
            if key.path.split(".", 1)[0] != group:
                continue
            presets = "; ".join(f"{label}: {_cell(v)}" for label, v in key.presets)
            L.append(f"| `{key.path}`{' (' + key.short + ')' if key.short else ''} | {key.type} | "
                     f"{_cell(key.default)} | {_domain(key)} | {key.apply} | {_guard(key)} | "
                     f"{_cell(key.help)} | {_cell(presets) if presets else ''} |")
        L.append("")
    L += ["## Retired v8 verbs (legacy runtime only, until S5)", "",
          "A legacy or unmigrated unit (e.g. the field units on `main`) still speaks v8. Its full "
          "reference: `git show 50e4586:docs/bmcam_command_reference.md`. A v8 line goes out "
          "unchecked with `tools/sofar_send_command.py --raw-message 'bm pub bmcam/cmd "
          "{\"id\":201,\"c\":\"twn\",\"v\":2} 1 1'` (window all day).", "",
          "| v8 | v9 |", "|---|---|"]
    L += [f"| `{old}` | {new} |" for old, new in RETIRED]
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--write", action="store_true", help=f"write {os.path.relpath(OUT, REPO)}")
    args = ap.parse_args(argv)
    text = render()
    if args.write:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"[REF] wrote {OUT} ({len(text.splitlines())} lines)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
